specific_payload = {
    "b64_related": {
        "eicar": [
            "b64_6char_per_line_eicar",
            "b64_junk_char_dot_eicar",
            "b64_junk_char_dash_eicar",
            "b64_junk_char_space_eicar",
            "b64_junk_char_pound_eicar",
            "b64_junk_char_4_dot_eicar",
            "b64_junk_char_4_eq_eicar",
            "b64_line_end_eq_eicar",
            "b64_split_1_eicar",
            "b64_split_2_eicar",
        ],
    },
    "qp_related": {
        "eicar": [
            "qp_blank_char_l09_eicar",
            "qp_blank_char_l20_eicar",
            "qp_blank_char_r09_eicar",
            "qp_blank_char_r20_eicar",
            "qp_lb_r_eicar",
            "qp_lb_n_eicar",
            "qp_lb_rrn_eicar",
            "qp_lb_rnn_eicar",
            "qp_illegal_char_09_eicar",
            "qp_illegal_char_12_eicar",
            "qp_illegal_char_aa_eicar",
            "qp_line_end_split_r_eicar",
            "qp_line_end_split_n_eicar",
            "qp_line_end_split_ern_eicar",
            "qp_line_end_e_eicar",
            "qp_line_end_e2_eicar",
            "qp_line_end_eat_eicar",
            "qp_line_end_e20e_eicar",
            "qp_inline_e_eicar",
            "qp_inline_e2_eicar",
            "qp_inline_eat_eicar",
            "qp_inline_e20e_eicar",
            "qp_inline_e09_eicar",
            "qp_inline_e12_eicar",
            "qp_inline_e0_eicar",
            "qp_inline_e0x_eicar",
            "qp_improper_hex_case_eicar",
            "qp_no_soft_lb_eicar",
            "qp_overlong_line_eicar",
        ],
    },
}
